ALTER TABLE IF EXISTS Artist AUTO_INCREMENT = 0;
ALTER TABLE IF EXISTS Genre AUTO_INCREMENT = 0;
ALTER TABLE IF EXISTS AlbumSong AUTO_INCREMENT = 0;
ALTER TABLE IF EXISTS AlbumArt AUTO_INCREMENT = 0;
ALTER TABLE IF EXISTS Song AUTO_INCREMENT = 0;
ALTER TABLE IF EXISTS `Format` AUTO_INCREMENT = 0;
ALTER TABLE IF EXISTS Inventory AUTO_INCREMENT = 0;